import { Montserrat, Prata } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  preload: true,
});

const prata = Prata({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prata",
  weight: ["400"],
  preload: true,
});

export const metadata = {
  title: "SecureCash | Convert CIT Provider",
  description: "Generated by create next app",
};

export default function RootLayout({ children })
{
  return (
    <html lang="en">
      <head>
        {/* ✅ CRITICAL: Preload first banner slide image - Mobile First! */}
        <link
          rel="preload"
          as="image"
          href="/images/banner/Slide-1-mobile.jpg"
          media="(max-width: 479px)"
          fetchpriority="high"
        />
        <link
          rel="preload"
          as="image"
          href="/images/banner/Slide-1-tablet.jpg"
          media="(min-width: 480px) and (max-width: 1023px)"
          fetchpriority="high"
        />
        <link
          rel="preload"
          as="image"
          href="/images/banner/Slide-1-web.jpg"
          media="(min-width: 1024px)"
          fetchpriority="high"
        />
      </head>
      <body className={`${montserrat.className} ${prata.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}