import { Montserrat, Prata} from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
  weight: ["300" ,"400", "500", "600", "700", "800", "900"],
  preload: true,
});
const prata = Prata({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prata",
  weight: ["400"],
  preload: true,
});



export const metadata = {
  title: "SecureCash | Convert CIT Provider",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ CRITICAL: Preload first slide images */}
        <link
          rel="preload"
          as="image"
          href="/images/banner/Slide-1-mobile.jpg"
          type="image/jpeg"
          media="(max-width: 479px)"
          fetchPriority="high"
        />
        <link
          rel="preload"
          as="image"
          href="/images/banner/Slide-1-tablet.jpg"
          type="image/jpeg"
          media="(min-width: 480px) and (max-width: 1023px)"
          fetchPriority="high"
        />
        <link
          rel="preload"
          as="image"
          href="/images/banner/Slide-1-web.jpg"
          type="image/jpeg"
          media="(min-width: 1024px)"
          fetchPriority="high"
        />

        {/* DNS/Preconnect */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link rel="dns-prefetch" href="https://www.securecash.com.au" />
      </head>
      <body className={`${montserrat.className} ${prata.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
